[General]
SyntaxVersion=2
BeginHotkey=32778
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=32775
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=66c58c34-71b0-40f2-804b-6f93f263fda4
Description=Åç»ðÉ±ºüÀê
Enable=0
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "7", 1
Delay 2300
KeyPress "Tab", 1
KeyPress "E", 1
Delay 4500
